apiVersion: v1
kind: Service
metadata:
  name: cart-microservice-service
  namespace: default
spec:
    selector:
        app: cart-microservice
    ports:
        - port: 5000
          targetPort: 5000