apiVersion: v1
kind: Service
metadata:
  name: product-microservice-service
  namespace: default
spec:
    selector:
        app: product-microservice
    ports:
        - port: 5000
          targetPort: 5000