apiVersion: v1
kind: Service
metadata:
  name: cart-microservice-service
  namespace: dev-namespace
spec:
   selector:
      app: cart-microservice
   type: NodePort
   ports:
       - port: 5000
         targetPort: 5000
         nodePort: 30112