apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
   - ../../base

patches:
   - path: cart-microservice-patch.yaml
   - path: product-microservice-patch.yaml
   - path: cart-microservice-service-patch.yaml
     target:
        kind: Service
        name: cart-microservice-service
   - path: product-microservice-service-patch.yaml
     target:
         kind: Service
         name: product-microservice-service

namespace: dev-namespace

replicas:
    - name: cart-microservice
      count: 2
    - name: product-microservice
      count: 2




namePrefix: dev-

labels:
   - includeSelectors: true
     pairs:
        env: dev
