apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-microservice
  namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: product-microservice
    template:
        metadata:
           labels:
               app: product-microservice
        spec:
           affinity:
              nodeAffinity:
                 requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                       - matchExpressions:
                          - key: custom-label
                            operator: In
                            values:
                               - proxmox
           containers:
           - name: product-microservice
             resources:
               requests:
                 memory: "64Mi"
                 cpu: "250m"
               limits:
                 memory: "128Mi"
                 cpu: "500m"
             image: PRODUCT_IMAGE_NAME
             ports:
               - containerPort: 5000
            